export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'


//FOR THE TASKLIST IN YOURSELF
export const USERS_ADD_TASKS="USERS_ADD_TASKS";
export const USERS_DONE_TASKS="USERS_DONE_TASKS";
export const CLEAR_TASKS_DATA="CLEAR_TASKS_DATA";
export const USER_STREAK_STATE_CHANGE = 'USER_STREAK_STATE_CHANGE';

export const NOTIF_ADD = "NOTIF_ADD"
export const CLEAR_NOTIF = "CLEAR_NOTIF"